const data = [
    {
        "id": 1,
        "image": "https://m.media-amazon.com/images/I/91ItZJh1FDL._SX679_.jpg",
        "pname": "Samsung Galaxy M34 5G",
        "category": "mobile",
        "brand": "samsung",
        "originalPrice": 24499,
        "offerPrice": 16548,
        "descript1": "16.42 Centimeters (6.5-Inch) Super AMOLED Display, FHD+ Resolution, 1080 x 2340 Pixels Protected by Corning Gorilla Glass 5",
        "descript2": "50MP+8MP+2MP Triple Camera Setup - True 50MP No Shake Cam (F1.8) Main Camera + 8MP (F2.2) + 2MP (F2.4)| 13MP (F2.0) Front Camera",
        "descript3": "6000mAH Lithium-ion battery, 1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for Inbox Accessories including batteries from the date of purchase",
        "descript4": "4 Generations of OS Upgrades and 5 Years of Security Updates",
        "descript5": "Exynos 1280 Octa Core 2.4GHz with the 12 Band Support for a True 5G Experience"
    },
    {
        "id": 2,
        "image": "https://m.media-amazon.com/images/I/71BiCb7N5YL._SX679_.jpg",
        "pname": "Xiaomi Redmi 10 Power",
        "category": "mobile",
        "brand": "redmi",
        "originalPrice": 18999,
        "offerPrice": 9899,
        "descript1": "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase",
        "descript2": "Upto 12GB RAM with RAM Plus | 64GB internal memory expandable up to 1TB| Dual Sim (Nano)",
        "descript3": "50MP+5MP+2MP Triple camera setup- True 50MP (F1.8) main camera +5MP(F2.2)+ 2MP (F2.4) | 8MP (F2.2) front cam",
        "descript4": "Android 12,One UI Core 4 with a powerful Octa Core Processor",
        "descript5": "16.72 centimeters (6.6-inch) FHD+ LCD - infinity O Display, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color"
    },
    {
        "id": 3,
        "image": "https://m.media-amazon.com/images/I/81PcAHZxgLL._SX569_.jpg",
        "pname": "Samsung Galaxy M13",
        "category": "mobile",
        "brand": "samsung",
        "originalPrice": 14999,
        "offerPrice": 9289,
        "descript1": "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase",
        "descript2": "Upto 12GB RAM with RAM Plus | 64GB internal memory expandable up to 1TB| Dual Sim (Nano)",
        "descript3": "50MP+5MP+2MP Triple camera setup- True 50MP (F1.8) main camera +5MP(F2.2)+ 2MP (F2.4) | 8MP (F2.2) front cam",
        "descript4": "Android 12,One UI Core 4 with a powerful Octa Core Processor",
        "descript5": "16.72 centimeters (6.6-inch) FHD+ LCD - infinity O Display, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color"
    },
    {
        "id": 4,
        "image": "https://m.media-amazon.com/images/I/41QssaE9gfL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "realme narzo N53",
        "category": "mobile",
        "brand": "realme",
        "originalPrice": 11999,
        "offerPrice": 10999,
        "descript1": "Enjoy smooth multitasking and effortless app switching with the powerful 12GB dynamic RAM. Store all your favorite apps, photos, and files with the generous 128GB ROM",
        "descript2": "Experience lightning-fast charging with the 33W SUPERVOOC technology, getting your device ready in no time. Say goodbye to long charging times and stay powered up for longer durations",
        "descript3": "The slim and sleek 7.49mm design adds a touch of elegance to your device, making it comfortable to hold and carry. The feather gold design enhances the visual appeal, giving your phone a premium and luxurious look.",
        "descript4": "Capture stunning, detailed photos with the high-resolution 50MP AI camera, bringing your memories to life.",
        "descript5": "he AI-powered camera technology ensures intelligent scene recognition and enhances your photography skills."
    },
    {
        "id": 5,
        "image": "https://m.media-amazon.com/images/I/41eSQvTbsaL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "OnePlus 11 5G",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 60000,
        "offerPrice": 58999,
        "descript1": "Camera: 50MP Main Camera with Sony IMX890 (OIS supported), 48MP Ultrawide Camera with Sony IMX581 (FOV: 115 degree) and 32MP Telephoto lens with Sony IMX709 (2X Optical Zoom); 16MP Front (Selfie) Camera with EIS support",
        "descript2": "Operating System: OxygenOS based on Android 13",
        "descript3": "Processor: Snapdragon 8 Gen 2 Mobile Platform",
        "descript4": "8GB LPDDR5X RAM, 128GB UFS3.1 Storage",
        "descript5": "Battery & Charging: 5000 mAh with 100W SUPERVOOC"
    },
    {
        "id": 6,
        "image": "https://m.media-amazon.com/images/I/41LMF7AU30L._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "iQOO Neo 7 Pro 5G",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 39999,
        "offerPrice": 32999,
        "descript1": "Snapdragon 8+ Gen 1 Mobile Platform adopts TSMC 4nm Process & has Superior Flagship Grade Performance with LPDDR5 RAM & UFS 3.1 Storage",
        "descript2": "Independent Gaming Chip boosts FPS by Game Frame Interpolation, sharpens Display with Game Display Enhancement and reduces power consumption",
        "descript3": "Takes only 8 min to charge from 1% to 50% with 120W FlashCharge in Fast Charging Mode (100% in 25 min)",
        "descript4": "Utmost clarity whether it’s Day or Night with Flagship 50MP GN5 OIS Ultra-Sensing coupled with Ultra-Wide (8MP) and Macro Camera",
        "descript5": "Motion Control, Gyroscope Enhancement, 4D Game Vibration, Voice Changer are here to level up your gaming experience"
    },
    {
        "id": 7,
        "image": "https://m.media-amazon.com/images/I/41Vq1rvptWL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "iQOO 9 5G",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 49990,
        "offerPrice": 42000,
        "descript1": "Qualcomm Snapdragon 888+ 5G Mobile Platform which is a 5nm process technology, the CPU performance is still 5.2% higher while maintaining the same power consumption",
        "descript2": "120W FlashCharge which can charge 50% battery in just 6 minutes and 100% battery in just 18 minutes.",
        "descript3": "Intelligent Display Chip is able to increase the frame rate and optimize colors so that every player can enjoy high FPS and rich colors at hand to be fully immersed in the gaming experience.",
        "descript4": "48MP Gimbal Camera system with Sony IMX598 sensor, 13MP super wide-angle camera can take wide-angle shots at 120° (108° after correction)",
        "descript5": "120Hz 10Bit AMOLED Display lets you enjoy a seamless and smooth screen experience, along with HDR 10+ Standard Certification that supports HDR high dynamic range video content playback."
    },
    {
        "id": 8,
        "image": "https://m.media-amazon.com/images/I/41etLpNZV6L._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "OnePlus 11R 5G",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 40999,
        "offerPrice": 39999,
        "descript1": "Camera: Sensor: 50MP Main Camera with Sony IMX890 (OIS supported), 8MP Ultrawide Camera (FOV: 120 degree) and Macro Lens; 16MP Front (Selfie) Camera with EIS support.",
        "descript2": "Display: 6.7 Inches; 120 Hz Super Fluid AMOLED; Resolution: 2772 X 1240 pixels ,450 ppi, 20.1:9, 10-bit Color Depth, HDR10+",
        "descript3": "Operating System: OxygenOS based on Android 13",
        "descript4": "Processor: Snapdragon 8+ Gen 1 Mobile Platform",
        "descript5": "8GB LPDDR5X RAM, 128GB UFS3.1 STORAGE"
    },
    {
        "id": 9,
        "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/t/h/galaxy-f54-5g-sm-e546bzshins-samsung-original-imagq79f82pfyzvh.jpeg?q=70",
        "pname": "SAMSUNG Galaxy F54 5G",
        "category": "mobile",
        "brand": "samsung",
        "originalPrice": 35999,
        "offerPrice": 24999,
        "descript1": "8 GB RAM | 256 GB ROM | Expandable Upto 1 TB",
        "descript2": "17.02 cm (6.7 inch) Full HD+ Display",
        "descript3": "108MP + 8MP + 2MP | 32MP Front Camera",
        "descript4": "6000 mAh Battery",
        "descript5": "Octa Core Processor"
    },
    {
        "id": 10,
        "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/d/r/-original-imagmym54wrhzgpn.jpeg?q=70",
        "pname": "SAMSUNG Galaxy A23 5G",
        "category": "mobile",
        "brand": "samsung",
        "originalPrice": 28999,
        "offerPrice": 20999,
        "descript1": "6 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
        "descript2": "16.76 cm (6.6 inch) Full HD+ Display",
        "descript3": "50MP + 5MP | 8MP Front Camera",
        "descript4": "5000 mAh Lithium Ion Battery",
        "descript5": "Qualcomm Snapdragon 695 (SM6375) Processor"
    },
    {
        "id": 11,
        "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/2/s/7/-original-imagmg6gktts6sfy.jpeg?q=70",
        "pname": "SAMSUNG Galaxy S23 Ultra 5G",
        "category": "mobile",
        "brand": "samsung",
        "originalPrice": 149999,
        "offerPrice": 124999,
        "descript1": "12 GB RAM | 256 GB ROM",
        "descript2": "17.27 cm (6.8 inch) Quad HD+ Display",
        "descript3": "200MP + 10MP + 12MP + 10MP | 12MP Front Camera",
        "descript4": "5000 mAh Lithium Ion Battery",
        "descript5": "Qualcomm Snapdragon 8 Gen 2 Processor"
    },
    {
        "id": 12,
        "image": "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/r/8/k/-original-imagtyxcgmgvtm7y.jpeg?q=70",
        "pname": "SAMSUNG Galaxy F14 5G",
        "category": "mobile",
        "brand": "samsung",
        "originalPrice": 18490,
        "offerPrice": 12490,
        "descript1": "6 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
        "descript2": "16.76 cm (6.6 inch) Full HD+ Display",
        "descript3": "50MP + 2MP | 13MP Front Camera",
        "descript4": "6000 mAh Battery",
        "descript5": "Exynos 1330, Octa Core Processor"
    },
    {
        "id": 13,
        "image": "https://m.media-amazon.com/images/I/41GsqdiCvOL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Redmi 12 5G",
        "category": "mobile",
        "brand": "redmi",
        "originalPrice": 15999,
        "offerPrice": 11999,
        "descript1": "Snapdragon 4 Gen 2 Mobile Platform : Power efficient 4nm architecture | 8GB of RAM including 4GB Virtual",
        "descript2": "Display: Large 17.24cm FHD+ 90Hz AdaptiveSync display with Corning Gorilla Glass 3 Protection",
        "descript3": "Camera: 50MP f/1.8 AI Dual camera with classic film filters, Film Frame, Portrait, Night Mode, 50MP mode, Time-lapse, Google lens | 8MP Selfie camera",
        "descript4": "5000mAh(typ) battery with 22.5W charger in-box",
        "descript5": "MIUI Dialer | MIUI 14 with Android 13 | Side fingerprint | IR blaster | 3.5mm Audio jack | IP53 rating"
    },
    {
        "id": 14,
        "image": "https://m.media-amazon.com/images/I/81guvfQzeVL._SX679_.jpg",
        "pname": "Redmi 12C",
        "category": "mobile",
        "brand": "redmi",
        "originalPrice": 13999,
        "offerPrice": 6999,
        "descript1": "Processor: High performance MediaTek Helio G85,upto 2Ghz; Enhanced gaming with 1GHz GPU | 4+3GB(Virtual RAM) LPDDR4x",
        "descript2": "Camera: 50MP f/1.8 AI Dual camera with Portrait mode & Night Mode | 5MP Selfie camera",
        "descript3": "Display: Large 17cm HD+ display with Scratch resistant Glass and Oleophobic coating | 500nits peak brightness",
        "descript4": "5000mAh(typ) battery with 10W charger in-box",
        "descript5": "Dual band Wifi support ensures better throughput and connectivity"
    },
    {
        "id": 15,
        "image": "https://m.media-amazon.com/images/I/71phm03oYhL._SY445_.jpg",
        "pname": "MI 10T 5G",
        "category": "mobile",
        "brand": "redmi",
        "originalPrice": 22999,
        "offerPrice": 12999,
        "descript1": "Processor: High performance MediaTek Helio G85,upto 2Ghz; Enhanced gaming with 1GHz GPU | 4+3GB(Virtual RAM) LPDDR4x",
        "descript2": "Camera: 50MP f/1.8 AI Dual camera with Portrait mode & Night Mode | 5MP Selfie camera",
        "descript3": "Display: Large 17cm HD+ display with Scratch resistant Glass and Oleophobic coating | 500nits peak brightness",
        "descript4": "5000mAh(typ) battery with 10W charger in-box",
        "descript5": "Dual band Wifi support ensures better throughput and connectivity"
    },
    {
        "id": 16,
        "image": "https://m.media-amazon.com/images/I/41LRhCMbApL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Redmi A2",
        "category": "mobile",
        "brand": "redmi",
        "originalPrice": 8999,
        "offerPrice": 6299,
        "descript1": "Processor: High performance MediaTek Helio G36,upto 2.2GHz; | Upto 4GB RAM including 2GB Virtual RAM | 32GB Storage",
        "descript2": "Display: Large 16.5 cm HD+ display with Scratch resistant glass | 400nits peak brightness | 120Hz Touch sampling Rate",
        "descript3": "Camera: 8MP Dual camera with Portrait mode | 5MP Front camera",
        "descript4": "5000mAh(typ) battery with 10W charger in-box",
        "descript5": "Expandable Storage to upto 1TB with Dedicated MicroSD card Slot | Dual SIM (nano+nano) dual standby (4G+4G)"
    },
    {
        "id": 17,
        "image": "https://m.media-amazon.com/images/I/81kra24lW5L._SY445_.jpg",
        "pname": "Redmi Xiaomi Note 7 Pro",
        "category": "mobile",
        "brand": "redmi",
        "originalPrice": 11799,
        "offerPrice": 15999,
        "descript1": "Processor: High performance MediaTek Helio G36,upto 2.2GHz; | Upto 4GB RAM including 2GB Virtual RAM | 32GB Storage",
        "descript2": "Display: Large 16.5 cm HD+ display with Scratch resistant glass | 400nits peak brightness | 120Hz Touch sampling Rate",
        "descript3": "Camera: 8MP Dual camera with Portrait mode | 5MP Front camera",
        "descript4": "5000mAh(typ) battery with 10W charger in-box",
        "descript5": "Expandable Storage to upto 1TB with Dedicated MicroSD card Slot | Dual SIM (nano+nano) dual standby (4G+4G)"
    },
    {
        "id": 18,
        "image": "https://m.media-amazon.com/images/I/61PJGlEw5nL._SY445_.jpg",
        "pname": "Redmi MI Xiaomi 11X 5G",
        "category": "mobile",
        "brand": "redmi",
        "originalPrice": 40999,
        "offerPrice": 39999,
        "descript1": "3.2GHz Octa Core Snapdragon 870 Processor",
        "descript2": "6.67 Inch FHD+ AMOLED Touchscreen Display",
        "descript3": "Camera: 8MP Dual camera with Portrait mode | 5MP Front camera",
        "descript4": "5000mAh(typ) battery with 10W charger in-box",
        "descript5": "Expandable Storage to upto 1TB with Dedicated MicroSD card Slot | Dual SIM (nano+nano) dual standby (4G+4G)"
    },
    {
        "id": 19,
        "image": "https://m.media-amazon.com/images/I/41pQ4gJMwEL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "OnePlus 10R 5G",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 40999,
        "offerPrice": 39999,
        "descript1": "Camera: 50MP Main Camera with Sony IMX766 and 2MP Macro Camera with Dual LED Flash; 16MP Front (Selfie) Camera with Sony IMX471",
        "descript2": "Display: 6.7 Inches; 120 Hz IRIS Display; Resolution: 2400 X 1080 pixels 394 ppi; Aspect Ratio: 20:9",
        "descript3": "Display Features: Hyper Touch Mode, Reading Mode, Night Mode, Eye Comfort Mode, Auto brightness",
        "descript4": "Operating System: OxygenOS based on Android 12, Processor: MTK D8100 Max",
        "descript5": "Battery & Charging: 5000 mAh with 80W SuperVOOC. In-Display Fingerprint Sensor"
    },
    {
        "id": 20,
        "image": "https://m.media-amazon.com/images/I/41Xe96WtZoL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "OnePlus Nord CE 3 Lite 5G",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 24999,
        "offerPrice": 19999,
        "descript1": "Camera: 108 MP Main Camera with EIS; 2MP Depth-Assist Lens and 2MP Macro Lens; Front (Selfie) Camera: 16MP",
        "descript2": "Operating System: Oxygen OS based on Android 13.1",
        "descript3": "Processor: Qualcomm Snapdragon 695 5G",
        "descript4": "Battery & Charging: 5000 mAh with 67W SUPERVOOC Endurance Editio",
        "descript5": "Rear Camera Mode: Hi-res 108MP mode, 3x Lossles Zoom, Photo, Video, Nightscape, Expert, Panoramic, Portrait, Macro, Time-lapse, Slow-motion, Long exposure, Dual-view video, Text Scanner, 1080p/720p@30fps"
    },
    {
        "id": 21,
        "image": "https://m.media-amazon.com/images/I/51UTlDMI0wL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "OnePlus 10T 5G",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 49999,
        "offerPrice": 39999,
        "descript1": "Camera: 50MP Main Camera with Sony IMX766 and OIS, 8MP Ultrawide Camera with 120 degree FOV and 2MP macro lens with LED Flash;",
        "descript2": "Display: 6.7 Inches; 120 Hz Fluid AMOLED Display with Corning Gorilla Glass; Resolution: 2412 X 1080 pixels; HDR 10+, sRGB, Display P3, 10-bit Color Depth",
        "descript3": "Processor: Snapdragon 8+ Gen 1 Mobile Platform",
        "descript4": "Operating System: OxygenOS based on Android 12",
        "descript5": "Battery & Charging: 4800 mAh with 150W SuperVOOC"
    },
    {
        "id": 22,
        "image": "https://m.media-amazon.com/images/I/51LByp9EsxL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Oneplus Open",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 149999,
        "offerPrice": 139999,
        "descript1": "Extraordinary materials blend the best of both. Titanium alloy, carbon fiber, and more. Built to the hilt with aerospace materials – with no expense spared. ",
        "descript2": "Dual ProXDR displays; Cover Display: 6.31” 2K resolution, Super Fluid AMOLED at 1440 Hz - Shielded by Ceramic Guard Dual-Displays: 7.82” 2K resolution, Flexi-fluid AMOLED 89.6% screen-to-body ratio at 1440 Hz - Shielded by Ultra Thin Glass",
        "descript3": "Processor: Qulacomm Snapdragon 8 Gen 2 Platform Ray tracing enabled",
        "descript4": "OxygenOS 13.2: Game-changing multitasking you’ll finally love using. Dual split screen and fast focus Drag and drop sharing Triple split-screen",
        "descript5": "Minimum crease. Maximum smooth. Our patented Flexion hinge mechanism, 8-axis pressure relief, and under-display micro-weaving significantly reduce creases."
    },
    {
        "id": 23,
        "image": "https://m.media-amazon.com/images/I/41eSQvTbsaL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "OnePlus 11 5G",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 71999,
        "offerPrice": 69999,
        "descript1": "Camera: 50MP Main Camera with Sony IMX890 (OIS supported), 48MP Ultrawide Camera with Sony IMX581 (FOV: 115 degree) and 32MP Telephoto lens with Sony IMX709 (2X Optical Zoom); 16MP Front (Selfie) Camera with EIS support",
        "descript2": "Operating System: OxygenOS based on Android 13",
        "descript3": "Processor: Snapdragon 8 Gen 2 Mobile Platform",
        "descript4": "16GB LPDDR5X RAM, 256 GB UFS4.0 Storage",
        "descript5": "Battery & Charging: 5000 mAh with 100W SUPERVOOC"
    },
    {
        "id": 24,
        "image": "https://m.media-amazon.com/images/I/41TmlehQnaL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "OnePlus Nord CE 3 5G",
        "category": "mobile",
        "brand": "oneplus",
        "originalPrice": 30999,
        "offerPrice": 26999,
        "descript1": "Camera: 50MP Main Camera with Sony IMX890 (OIS supported), 8MP Ultrawide Camera with Sony IMX355 (FOV: 112 degree) and 2MP Macro lens; 16MP Front (Selfie) Camera",
        "descript2": "Camera Features: Ultra Steady Mode, Dual-view Video, HDR, Nightscape, Portrait Mode, Video Portrait, Pano, Macro, Slo-mo, Time-lapse, Text-scanner, Retouching, Filters, Google Lens, Extra HD, Pro Mode",
        "descript3": "Display: 6.7 Inches; 120 Hz AMOLED FHD+, Resolution: 2412 x 1080 pixels; HDR 10+, sRGB, 10-bit Color Depth, 93.4% Screen to body ratio",
        "descript4": "Operating System: OxygenOS 13 based on Android 13.1",
        "descript5": "Processor: Qualcomm Snapdragon 782G Mobile Platform"
    },
    {
        "id": 25,
        "image": "https://m.media-amazon.com/images/I/81WimZLWH1L._SX425_.jpg",
        "pname": "realme narzo 60X 5G",
        "category": "mobile",
        "brand": "realme",
        "originalPrice": 15999,
        "offerPrice": 14999,
        "descript1": "50MP Primary Camera,street photography high-quality pictures that catch every details with astounding clarity",
        "descript2": "Fast refresh displays cut blur in animations, scrolling and games to provide a notably better user experience. ",
        "descript3": "According to the installation of a photo 4M to calculate: 128GB of memory can be installed 28000 + photos； According to a 720P TV series size of 250M to calculate: 128GB memory can be loaded with 450 + TV series",
        "descript4": "With a 33 W Powerful SUPERVOOC Charge, 30 minutes charge for 50% battery and full charge in 70 minutes,5000mAh massive battery, without ever being concerned about the battery running out",
        "descript5": "Processor: Qualcomm Snapdragon 782G Mobile Platform"
    },
    {
        "id": 26,
        "image": "https://m.media-amazon.com/images/I/61ID345p2jL._SX385_.jpg",
        "pname": "realme C53",
        "category": "mobile",
        "brand": "realme",
        "originalPrice": 9999,
        "offerPrice": 7999,
        "descript1": "【RAM, ROM And Expandable】:- 4 GB RAM | 128 GB ROM | Expandable Upto 2 TB",
        "descript2": "【Display】:- 17.12 cm (6.74 inch) HD Display | 17.13 cm Screen SIze with 90 Hz Display | The large screen size of 17.13 cm with 90 Hz display",
        "descript3": "【Camera】:- 108MP + 2MP | 8MP Front Camera | Enhance your photography skills with this C53 smartphone having 108 MP ultra clear camera.",
        "descript4": "【Processor】:- T612 Processor | Smart Octa-core Chipset | The processing speed of your phone is improved with the strong and powerful octa-core chipset.",
        "descript5": "【Battery】:- 5000 mAh Large Battery With 18 W Fast Charger | Powered with a large battery of 5000 mAh,"
    },
    {
        "id": 27,
        "image": "https://m.media-amazon.com/images/I/71JPbL+lnXL._SY355_.jpg",
        "pname": "realme GT Neo 3",
        "category": "mobile",
        "brand": "realme",
        "originalPrice": 46999,
        "offerPrice": 26899,
        "descript1": "12 GB RAM | 256 GB ROM; 17.02 cm (6.7 inch) Full HD+ Display",
        "descript2": "50MP + 8MP + 2MP | 16MP Front Camera",
        "descript3": "4500 mAh Lithium Ion Battery",
        "descript4": "Mediatek Dimensity 8100 Processor",
        "descript5": "Display Type: Oled"
    },
    {
        "id": 28,
        "image": "https://m.media-amazon.com/images/I/41EzGyFJ2LL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "realme narzo 60 5G",
        "category": "mobile",
        "brand": "realme",
        "originalPrice": 19999,
        "offerPrice": 17999,
        "descript1": "Immerse yourself in a smooth and responsive visual experience with our vibrant 90Hz Super AMOLED display. ",
        "descript2": "Unleash your creativity and capture stunning street photography moments with our powerful 64 MP camera. ",
        "descript3": "Embrace the sleekness of our ultra-slim design, measuring only 7.93mm in thickness.",
        "descript4": "Android 13.0",
        "descript5": "4500 mAh Lithium Ion Battery"
    },
    {
        "id": 29,
        "image": "https://m.media-amazon.com/images/I/819bwF7gjfL._SX425_.jpg",
        "pname": "realme narzo 50i Prime",
        "category": "mobile",
        "brand": "realme",
        "originalPrice": 9999,
        "offerPrice": 8999,
        "descript1": "Display: 6.5 inch HD+ display with 400nits of brightness brings a full screen display and vibrant colors to make every ounce of the experience exciting.",
        "descript2": "8MP back camera for crisp and clear shots and 5MP front camera picture perfect selfie",
        "descript3": "5000mAh Massive Battery with 10W fast charging support. The 10W fast charger is included in the box.",
        "descript4": "4 GB RAM LPDDR4X Fast memory | 64 GB ROM UFS 2.2 | External storage is Expandable Up to 1TB",
        "descript5": "Powerful Unisoc T612 processor for smooth day to day performance |Superb performance with an AnTuTu Benchmark Score of 214, 150 | Power efficient "
    },
    {
        "id": 30,
        "image": "https://m.media-amazon.com/images/I/61Id6WJDWqL._SX425_.jpg",
        "pname": "iQOO Z7 Pro 5G",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 27999,
        "offerPrice": 24999,
        "descript1": "Dimensity 7200 5g processor based on the latest 4nm energy-efficient process",
        "descript2": "3D Curved Super-vision Display with 17.22 cm (6.78 inches) screen size, 93.3% Screen-to-body ratio, 120 Hz AMOLED FHD+, 1.07 Billion Colors, 1300 nits Peak Local Brightness",
        "descript3": "Slimmest phone with 0.736 cm (7.36mm) thickness, Premium AG Matte Glass finish",
        "descript4": "64 MP AURA Light OIS Camera, 4K video recording, Hybrid Image Stabilization, Super Night Mode, Aura Light Portrait, Camera Panning Portrait",
        "descript5": "66W FlashCharge with 4600mAh large battery | 8GB RAM + 8GB Extended RAM"
    },
    {
        "id": 31,
        "image": "https://m.media-amazon.com/images/I/61JS7lF2aqL._SX425_.jpg",
        "pname": "iQOO Neo 7 5G",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 34999,
        "offerPrice": 27999,
        "descript1": "MediaTek Dimensity 8200 5G Mobile platform adopts TSMC 4nm process and has excellent Power Efficiency Performance. Also, Equipped with the LPDDR5 RAM & UFS 3.1 Storage.",
        "descript2": "The 120W FlashCharge charges from 1% to 50% in just 10 minutes (25 minutes for a full charge",
        "descript3": "Motion Control powered by Gyroscope & Acceleration Sensors to give 6 additional Phone movement-based control options while Gaming",
        "descript4": "6.78” 120Hz AMOLED Display with HDR 10+ Certification, Netflix HDR Support & 1300 Nits Peak Brightness",
        "descript5": "64MP OIS Camera, Dual Stereo Speakers, X-Axis Linear Motor and Extended RAM 3.0 (8GB+8GB)"
    },
    {
        "id": 32,
        "image": "https://m.media-amazon.com/images/I/712pLRfzDYL._SX425_.jpg",
        "pname": "iQOO Neo 7 Pro 5G",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 42999,
        "offerPrice": 35999,
        "descript1": "Snapdragon 8+ Gen 1 Mobile Platform adopts TSMC 4nm Process & has Superior Flagship Grade Performance with LPDDR5 RAM & UFS 3.1 Storage",
        "descript2": "Takes only 8 min to charge from 1% to 50% with 120W FlashCharge in Fast Charging Mode (100% in 25 min)",
        "descript3": "Utmost clarity whether it’s Day or Night with Flagship 50MP GN5 OIS Ultra-Sensing coupled with Ultra-Wide (8MP) and Macro Camera",
        "descript4": "Motion Control, Gyroscope Enhancement, 4D Game Vibration, Voice Changer are here to level up your gaming experience",
        "descript5": "Independent Gaming Chip boosts FPS by Game Frame Interpolation, sharpens Display with Game Display Enhancement and reduces power consumption"
    },
    {
        "id": 33,
        "image": "https://m.media-amazon.com/images/I/51oW-QOqhaL._SX425_.jpg",
        "pname": "iQOO Z7s 5G by vivo",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 24999,
        "offerPrice": 17999,
        "descript1": "Snapdragon 695 5G Mobile Processor with a 6nm energy efficient process which will consume less power and enhance the battery life",
        "descript2": "6.38 inches FHD+ AMOLED display, 1300 nits peak local brightness, 90 Hz refresh rate, Schott Xensation UP glass protection, IP54 rated",
        "descript3": "64MP OIS Ultra Stable Camera; 2MP Bokeh camera; Front (Selfie) Camera: 16MP",
        "descript4": "44W FlashCharge, 50% charge in just 23 minutes 11 seconds. Ultra Game Mode, Motion Control, and 1200Hz Instant touch sampling rate for immersive gaming",
        "descript5": "Camera Features: Ultra Stabilization video recording, Micro Movie Mode, Dual View Video, Night Mode, Portrait mode, Double Exposure, Panorama Mode, Pro mode, 1080p video at 60 fps"
    },
    {
        "id": 34,
        "image": "https://m.media-amazon.com/images/I/61lWkGr0RiL._SX425_.jpg",
        "pname": "iQOO 9 Pro 5G",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 79990,
        "offerPrice": 69989,
        "descript1": "Snapdragon️ 8 Gen 1 Mobile Processor which uses the latest 4nm process technology & has a maximum increase of 20% in CPU performance, a maximum increase of 30% in GPU performance",
        "descript2": "120W FlashCharge which can charge 50% battery in just 8 minutes and 100% battery in just 20 minutes.",
        "descript3": "Intelligent Display Chip which increases the frame rate and optimize colors so that every player can enjoy high FPS and rich colors",
        "descript4": "3D Ultrasonic Large Fingerprint Sensor which will help users in Unlocking without light: Better user experience at night, High security",
        "descript5": "50MP GN5 Gimbal Camera which is equipped with GN5's all-directional autofocus technology"
    },
    {
        "id": 35,
        "image": "https://m.media-amazon.com/images/I/61VbKHdE0rL._SX342_.jpg",
        "pname": "iQOO Z6 Lite 5G",
        "category": "mobile",
        "brand": "iqoo",
        "originalPrice": 19999,
        "offerPrice": 12999,
        "descript1": "Snapdragon 695 5G Mobile Processor with a 6nm energy efficient process which will consume less power and enhance the battery life",
        "descript2": "6.38 inches FHD+ AMOLED display, 1300 nits peak local brightness, 90 Hz refresh rate, Schott Xensation UP glass protection, IP54 rated",
        "descript3": "64MP OIS Ultra Stable Camera; 2MP Bokeh camera; Front (Selfie) Camera: 16MP",
        "descript4": "44W FlashCharge, 50% charge in just 23 minutes 11 seconds. Ultra Game Mode, Motion Control, and 1200Hz Instant touch sampling rate for immersive gaming",
        "descript5": "Camera Features: Ultra Stabilization video recording, Micro Movie Mode, Dual View Video, Night Mode, Portrait mode, Double Exposure, Panorama Mode, Pro mode, 1080p video at 60 fps"
    },
    {
        "id": 36,
        "image": "https://m.media-amazon.com/images/I/51JtPyNUfoL._SY450_.jpg",
        "pname": "WOW IMAGINE Shock Proof Back Case Mobile Cover",
        "category": "case",
        "brand": "oneplus",
        "originalPrice": 999,
        "offerPrice": 799,
        "descript1": "360 Degree Protection : This Sturdy Armor Case has a Rugged Construction which provides the phone All-Round Protection. Raised Lips on Front & Back provide Proper Camera & Screen Protection.",
        "descript2": "Ring Holder : Innovative Ring Holder Design is Highly Adjustable which allows you to hold phone with Extreme Ease & Comfort.",
        "descript3": "In-Built Stand: The Inbuilt Stand Provides you a Handsfree Experience while watching any Movie or Video Content.",
        "descript4": "Compatible Phone Models:	OnePlus Nord CE 3 Lite 5G",
        "descript5": "Car Magnetic Holder : A High Quality Metal Strip is Installed in this case which makes it Magnetically Compatible with that Magnetic Car Holder in your Car."
    },
    {
        "id": 37,
        "image": "https://m.media-amazon.com/images/I/51Q2IT5SrvL._SY355_.jpg",
        "pname": "VMT STOCK WITH DEVICE Shock Proof Clear Back Cover Case",
        "category": "case",
        "brand": "oneplus",
        "originalPrice": 499,
        "offerPrice": 257,
        "descript1": "ANTI FINGERPRINT & NEVER YELLOW- This phone case for OnePlus Nord CE 2 Lite 5G can effectively avoid discoloration problem, without fear of fingerprints, oil, and coffee stains, thus maintaining a timeless fresh appearance.",
        "descript2": "PREMIUM PROTECTION - Soft rubber silicon material protection to prevent and shield your mobile from scratches, falls, dust and debris. It offers complete backside protection.",
        "descript3": "SLIM AND SLEEK DESIGEN- The protective phone case for OnePlus Nord CE 2 Lite 5G being a perfect blend of sleek, slim design and drop protection for everyday use.",
        "descript4": "360° FULL BODY PROTECTION- This protective case is composed of hard PC back and soft TPU bumper protect your phone from scratches, bump,shock and other elements in daily use.",
        "descript5": "PRECISE CUTOUTS- Take pictures, listen to music, charge your phone, and use your side buttons without removing the case!"
    },
    {
        "id": 38,
        "image": "https://m.media-amazon.com/images/I/71igsTYXCML._SY450_.jpg",
        "pname": "MOSHKING Thermoplastic Polyurethane Back Cover",
        "category": "case",
        "brand": "samsung",
        "originalPrice": 999,
        "offerPrice": 499,
        "descript1": "[COMPATIBLE MODEL]:This phone case is compatible with Samsung Galaxy A34 5G not for other phone models. Please remove the case before using wireless charger because this case does not support wireless charging.",
        "descript2": "[Slide Camera Lens Cover]:Delicate camera lens sliding cover, higher than the raised camera. ",
        "descript3": "[Metal Ring Kickstand]:This protective phone cover with a built-in metal ring stand can rotate 360°, gives you the convenience",
        "descript4": "[Military-Grade Drop Protection]:Certified 10ft drop test, unique shock absorption design drop protection.This case is made with a hard PC tough back and flexible Soft TPU shock-absorbing bumpers",
        "descript5": "[Product Service]:The non-slip bumper provides excellent grip and prevents your phone from slipping out of your hand. Please rest assured that information to buy!"
    },
    {
        "id": 39,
        "image": "https://m.media-amazon.com/images/I/41Nl6z4xjZL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Pikkme Flip Cover for Samsung",
        "category": "case",
        "brand": "samsung",
        "originalPrice": 999,
        "offerPrice": 199,
        "descript1": "Premium & High Finish Product : Pikkme Leather Case for Samsung Galaxy M31 are high quality product which offer soft touch and timeless design.",
        "descript2": "Precise Cut-Out : Pikkme Leather Case are provided with high quality and precious cut-outs for all ports . ",
        "descript3": "Ultimate Protection & Magnetic Flip : These cases provide great protection to your device from front and back side and also it comes with magnetic flip to keep the case closed while kept idle.",
        "descript4": "Kick back and relax with a kick-stand engineered into the design of Pikkme leather case.",
        "descript5": "deal Gifting Product: These high quality premium leather cases are suited as gifting item for your loved ones ."
    },
    {
        "id": 40,
        "image": "https://m.media-amazon.com/images/I/41eqr1keWbL._SY355_.jpg",
        "pname": "65w Charger Warp/Dash/SUPERVOOC Charger",
        "category": "charger",
        "brand": "oneplus",
        "originalPrice": 1999,
        "offerPrice": 999,
        "descript1": "This Oneplus 65W Warp Charger Supports Warp Charge 65, SUPERVOOC 65w, Warp Charge 30, Oneplus Dash Fast Charge And Regular Charging Speed Of Other Devices. ",
        "descript2": "Warps/Dash Charging Cable: The Warp65 Usb-C Charging Cable Can Quickly Charge Oneplus Phone. ",
        "descript3": "Warp/SuperVooc Charger: 65 Watt Charger For Oneplus Is Fastest Charging Technology, Including Support For Oneplus",
        "descript4": "Safe And Reliable: When Charging The Oneplus 11/11r/10/10r/9/9 Pro/8T/8T/Nord/CE, The Warp 65W/SUPERVOOC/VOOC/DASH Flash Will Be Turned On The Display Screen.",
        "descript5": "65w Warp Charger - Specially Designed For Newest Oneplus 11/11r/10/10r/8T/9/9 Pro/NORD/CE"
    },
    {
        "id": 41,
        "image": "https://m.media-amazon.com/images/I/21uXmiH98wL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Samsung Original 25W Single Port, Type-C Fast Charger",
        "category": "charger",
        "brand": "samsung",
        "originalPrice": 1699,
        "offerPrice": 999,
        "descript1": "Charging Cable Not Included. Compatible With All Standard Usb Type-C Cables Such As Usb-C To Usb-C, Usb-C To Lightning And Etc",
        "descript2": "Enjoy The Flexibility Enabled By Usb-C Compatible Cables. You Can Alternate ",
        "descript3": "Enjoy The Flexibility Of The Usb Type-C; Super Fast Charging To Stay Ready",
        "descript4": "Give Your Mobile Devices The Powerful And Safe Charging Support They Deserve.",
        "descript5": "Included Components: Wall Charger, User Manual; Power Source Type: Corded Electric"
    },
    {
        "id": 42,
        "image": "https://m.media-amazon.com/images/I/311RudVWO8L._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Orginal Samsung 25W Pd Charging Adapter",
        "category": "charger",
        "brand": "samsung",
        "originalPrice": 1999,
        "offerPrice": 699,
        "descript1": "25W WHITE CHARGRE WITH WHITE TYPE C CABLE",
        "descript2": "Enjoy The Flexibility Enabled By Usb-C Compatible Cables. You Can Alternate ",
        "descript3": "Enjoy The Flexibility Of The Usb Type-C; Super Fast Charging To Stay Ready",
        "descript4": "Give Your Mobile Devices The Powerful And Safe Charging Support They Deserve.",
        "descript5": "Included Components: Wall Charger, User Manual; Power Source Type: Corded Electric"
    },
    {
        "id": 43,
        "image": "https://m.media-amazon.com/images/I/31Bfl8lSdJL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Amazon Basics 30W Dual Port GaN Charger",
        "category": "charger",
        "brand": "iqoo",
        "originalPrice": 2999,
        "offerPrice": 1369,
        "descript1": "LATEST GAN CHIP TECHNOLOGY: GaN Technology makes chargers three times more efficient than regular silicon-based chargers",
        "descript2": "DUAL PORT CHARGING: This 30W charger has a USB-C and A port for charging 2 devices at the same time. Compatible with Apple, Samsung, Huawei, Xiaomi, OnePlus and Google and other charge protocols such as PD3.0, PD2.0, QC2.0, QC3.0, AFC, FCP and PPS.",
        "descript3": "OPTIMISED CHARGING: The built-in intelligent chip adjusts the output voltage when multiple devices are being charged at the same time across the ports to make charging safe and efficient.",
        "descript4": "FOLDABLE PINS: The sleek design and compact size comes with a foldable pin to make this charger portable and travel-friendly for both Indian and US sockets.",
        "descript5": "SUPER COMPACT: The dual port charger is 45% smaller than a traditional 30W charger box. Its smart cube design fits easily into plug points without taking additional space."
    },
    {
        "id": 44,
        "image": "https://m.media-amazon.com/images/I/61VuVU94RnL._SX522_.jpg",
        "pname": "Apple iPhone 13 (128GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone13",
        "originalPrice": 69999,
        "offerPrice": 51499,
        "descript1": "15 cm (6.1-inch) Super Retina XDR display",
        "descript2": "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
        "descript3": "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
        "descript4": "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
        "descript5": "A15 Bionic chip for lightning-fast performance"
    },
    {
        "id": 45,
        "image": "https://m.media-amazon.com/images/I/71gm8v4uPBL._SX522_.jpg",
        "pname": "Apple iPhone 13 (256GB) ",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone13",
        "originalPrice": 69999,
        "offerPrice": 60999,
        "descript1": "15 cm (6.1-inch) Super Retina XDR display",
        "descript2": "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
        "descript3": "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
        "descript4": "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
        "descript5": "A15 Bionic chip for lightning-fast performance"
    },
    {
        "id": 46,
        "image": "https://m.media-amazon.com/images/I/71xb2xkN5qL._SX522_.jpg",
        "pname": "Apple iPhone 13 (512GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone13",
        "originalPrice": 89999,
        "offerPrice": 69499,
        "descript1": "15 cm (6.1-inch) Super Retina XDR display",
        "descript2": "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
        "descript3": "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
        "descript4": "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
        "descript5": "A15 Bionic chip for lightning-fast performance"
    },
    {
        "id": 47,
        "image": "https://m.media-amazon.com/images/I/61J9KUops4L._SX522_.jpg",
        "pname": "Apple iPhone 13 Mini (256 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone13",
        "originalPrice": 49999,
        "offerPrice": 39999,
        "descript1": "15 cm (6.1-inch) Super Retina XDR display",
        "descript2": "Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
        "descript3": "Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
        "descript4": "12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
        "descript5": "A15 Bionic chip for lightning-fast performance"
    },
    {
        "id": 48,
        "image": "https://m.media-amazon.com/images/I/31eq5m7D5uL._SY445_SX342_QL70_FMwebp_.jpg",
        "pname": "Apple iPhone SE (64 GB)",
        "category": "mobile",
        "brand": "apple",
        "originalPrice": 40999,
        "offerPrice": 38999,
        "descript1": "11.94 cm (4.7-inch) Retina HD display",
        "descript2": "Advanced single-camera system with 12MP Wide camera; Smart HDR 4, Photographic Styles, Portrait mode, and 4K video up to 60 fps",
        "descript3": "A15 Bionic chip for lightning-fast performance",
        "descript4": "iOS 15 packs new features to do more with iPhone than ever before",
        "descript5": "Durable design and IP67 water resistance"
    },
    {
        "id": 49,
        "image": "https://m.media-amazon.com/images/I/61bK6PMOC3L._SX425_.jpg",
        "pname": "Apple iPhone 14 (128 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone14",
        "originalPrice": 40999,
        "offerPrice": 38999,
        "descript1": "15.40 cm (6.1-inch) Super Retina XDR display",
        "descript2": "Advanced camera system for better photos in any light",
        "descript3": "Cinematic mode now in 4K Dolby Vision up to 30 fps",
        "descript4": "All-day battery life and up to 20 hours of video playback",
        "descript5": "Industry-leading durability features with Ceramic Shield and water resistance"
    },
    {
        "id": 50,
        "image": "https://m.media-amazon.com/images/I/71ZDY57yTQL._SX522_.jpg",
        "pname": "Apple iPhone 14 Pro (256 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone14",
        "originalPrice": 139999,
        "offerPrice": 129999,
        "descript1": "15.54 cm (6.1-inch) Super Retina XDR display featuring Always-On and ProMotion",
        "descript2": "Dynamic Island, a magical new way to interact with iPhone",
        "descript3": "48MP Main camera for up to 4x greater resolution",
        "descript4": "Cinematic mode now in 4K Dolby Vision up to 30 fps",
        "descript5": "All-day battery life and up to 23 hours of video playback"
    },
    {
        "id": 51,
        "image": "https://m.media-amazon.com/images/I/61BGE6iu4AL._SX425_.jpg",
        "pname": "Apple iPhone 14 Plus (128 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone14",
        "originalPrice": 129999,
        "offerPrice": 111999,
        "descript1": "16.95 cm (6.7-inch) Super Retina XDR display",
        "descript2": "Advanced camera system for better photos in any light",
        "descript3": "All-day battery life and up to 26 hours of video playback",
        "descript4": "Industry-leading durability features with Ceramic Shield and water resistance",
        "descript5": "Action mode for smooth, steady, handheld videos"
    },
    {
        "id": 52,
        "image": "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX425_.jpg",
        "pname": "Apple iPhone 15 (256 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone15",
        "originalPrice": 87900,
        "offerPrice": 85000,
        "descript1": "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution",
        "descript2": "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities",
        "descript3": "POWERHOUSE A16 BIONIC CHIP — The superfast chip powers advanced features like computational photography, fluid Dynamic Island transitions, and Voice Isolation for phone calls. And A16 Bionic is incredibly efficient to help deliver great all-day battery life.",
        "descript4": "NEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color. Just tap to shift the focus between subjects — even after you take the shot.",
        "descript5": "INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design."
    },
    {
        "id": 53,
        "image": "https://m.media-amazon.com/images/I/71v2jVh6nIL._SX425_.jpg",
        "pname": "Apple iPhone 15 (128 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone15",
        "originalPrice": 79990,
        "offerPrice": 77999,
        "descript1": "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution",
        "descript2": "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities",
        "descript3": "POWERHOUSE A16 BIONIC CHIP — The superfast chip powers advanced features like computational photography, fluid Dynamic Island transitions, and Voice Isolation for phone calls. And A16 Bionic is incredibly efficient to help deliver great all-day battery life.",
        "descript4": "NEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color. Just tap to shift the focus between subjects — even after you take the shot.",
        "descript5": "INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design."
    },
    {
        "id": 54,
        "image": "https://m.media-amazon.com/images/I/71REplb5oZL._SX425_.jpg",
        "pname": "Apple iPhone 15 (512 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone15",
        "originalPrice": 109999,
        "offerPrice": 107999,
        "descript1": "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution",
        "descript2": "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities",
        "descript3": "POWERHOUSE A16 BIONIC CHIP — The superfast chip powers advanced features like computational photography, fluid Dynamic Island transitions, and Voice Isolation for phone calls. And A16 Bionic is incredibly efficient to help deliver great all-day battery life.",
        "descript4": "NEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color. Just tap to shift the focus between subjects — even after you take the shot.",
        "descript5": "INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design."
    },
    {
        "id": 55,
        "image": "https://m.media-amazon.com/images/I/71zFRCcMS2L._SX425_.jpg",
        "pname": "Apple iPhone 15 Plus (128 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone15",
        "originalPrice": 89990,
        "offerPrice": 87990,
        "descript1": "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution",
        "descript2": "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities",
        "descript3": "POWERHOUSE A16 BIONIC CHIP — The superfast chip powers advanced features like computational photography, fluid Dynamic Island transitions, and Voice Isolation for phone calls. And A16 Bionic is incredibly efficient to help deliver great all-day battery life.",
        "descript4": "NEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color. Just tap to shift the focus between subjects — even after you take the shot.",
        "descript5": "INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design."
    },
    {
        "id": 56,
        "image": "https://m.media-amazon.com/images/I/81fxjeu8fdL._SX425_.jpg",
        "pname": "Apple iPhone 15 Pro Max (256 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone15",
        "originalPrice": 159999,
        "offerPrice": 139999,
        "descript1": "FORGED IN TITANIUM — iPhone 15 Pro Max has a strong and light aerospace-grade titanium design with a textured matte-glass back. It also features a Ceramic Shield front that’s tougher than any smartphone glass. And it’s splash, water, and dust resistant.",
        "descript2": "ADVANCED DISPLAY — The 6.7” Super Retina XDR display with ProMotion ramps up refresh rates to 120Hz when you need exceptional graphics performance. ",
        "descript3": "GAME-CHANGING A17 PRO CHIP — A Pro-class GPU makes mobile games feel so immersive, with rich environments and realistic characters.",
        "descript4": "POWERFUL PRO CAMERA SYSTEM — Get incredible framing flexibility with 7 pro lenses. Capture super high-resolution photos with more color and detail using the 48MP Main camera.",
        "descript5": "CUSTOMIZABLE ACTION BUTTON — Action button is a fast track to your favorite feature. Just set the one you want, like Silent mode, Camera, Voice Memo, Shortcut, and more. Then press and hold to launch the action."
    },
    {
        "id": 57,
        "image": "https://m.media-amazon.com/images/I/81qlME2wWmL._SX425_.jpg",
        "pname": "Apple iPhone 15 Pro (1 TB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone15",
        "originalPrice": 194999,
        "offerPrice": 184999,
        "descript1": "FORGED IN TITANIUM — iPhone 15 Pro Max has a strong and light aerospace-grade titanium design with a textured matte-glass back. It also features a Ceramic Shield front that’s tougher than any smartphone glass. And it’s splash, water, and dust resistant.",
        "descript2": "ADVANCED DISPLAY — The 6.7” Super Retina XDR display with ProMotion ramps up refresh rates to 120Hz when you need exceptional graphics performance. ",
        "descript3": "GAME-CHANGING A17 PRO CHIP — A Pro-class GPU makes mobile games feel so immersive, with rich environments and realistic characters.",
        "descript4": "POWERFUL PRO CAMERA SYSTEM — Get incredible framing flexibility with 7 pro lenses. Capture super high-resolution photos with more color and detail using the 48MP Main camera.",
        "descript5": "CUSTOMIZABLE ACTION BUTTON — Action button is a fast track to your favorite feature. Just set the one you want, like Silent mode, Camera, Voice Memo, Shortcut, and more. Then press and hold to launch the action."
    },
    {
        "id": 58,
        "image": "https://m.media-amazon.com/images/I/517zhdulvlL._SY450_.jpg",
        "pname": "Hard Back Transparent Cover Case",
        "category": "icase",
        "brand": "apple",
        "originalPrice": 1499,
        "offerPrice": 284,
        "descript1": "Compatible with iPhone 14 and iPhone 13 Only",
        "descript2": "Color: Transparent + Black Bumper",
        "descript3": "Polycarbonate hard back + Soft bumper makes it anti yellow",
        "descript4": "Big camera of iPhone is protected with raised ring",
        "descript5": "Ultra slim and crystal clear design make it minimalistic on phone"
    },
    {
        "id": 59,
        "image": "https://m.media-amazon.com/images/I/6118YQPQZlL._SY550_.jpg",
        "pname": "Protection Back Cover Case for iPhone 13",
        "category": "icase",
        "brand": "apple",
        "originalPrice": 1499,
        "offerPrice": 289,
        "descript1": "QUALITY MATERIAL - Hybrid technology that is made of a TPU Material with a durable back panel",
        "descript2": "CAMERA PROTECTION - Raised bezels lift camera off flat surfaces",
        "descript3": "PRECISE CUTOUTS - Pronounced buttons are easy to feel and press, while large cutouts fit most cables",
        "descript4": "MODERN DESIGN - Elegant Design perfectly uses the advantages of the scratch-resistant PC plate and the flexible TPU",
        "descript5": "Compatible with iPhone 13 Case Cover (6.1)"
    },
    {
        "id": 60,
        "image": "https://m.media-amazon.com/images/I/71qdwvOL5SL._SY450_.jpg",
        "pname": "Spigen Liquid Air Back Cover Case",
        "category": "icase",
        "brand": "apple",
        "originalPrice": 2999,
        "offerPrice": 1299,
        "descript1": "[Compatibility] Spigen Genuine Case Compatible with iPhone 15",
        "descript2": "[Modern design] Modern style pattern design for fingerprint resistance and minimal look",
        "descript3": "[Protection] Air Cushion Technology for shock absorption",
        "descript4": "[Precise Fit] Form-fitted to maintain a slim profile and pocket-friendly",
        "descript5": "[Material] Made of high-quality TPU"
    },
    {
        "id": 61,
        "image": "https://m.media-amazon.com/images/I/71Yu2V98EjL._SY450_.jpg",
        "pname": "Spigen Capella Mag Kickstand Back Cover Case",
        "category": "icase",
        "brand": "apple",
        "originalPrice": 4999,
        "offerPrice": 2699,
        "descript1": "[Comfortable View] The case features a metal hinge equipped with a kickstand, providing a stable stand function; It provides diverse and secure viewing angles with a maximum opening angle of 58°; Enjoy the convenience of using the kickstand for various purposes",
        "descript2": "[Built-in Kickstand] The built-in kickstand is seamlessly integrated to sit flush with the back, ensuring no protrusion for a hassle-free user experience; It perfectly supports MagSafe accessories, allowing for seamless utilization; With its strong magnetic force, it provides complete protection for your accessories, ensuring a perfect fit",
        "descript3": "[Express Your Uniqueness] Through color matching with MagSafe and the kickstand, we have achieved a sense of unity, while the colored glass on the kickstand's front blends harmoniously with the case, offering a distinct hue for expressing your individuality; Explore the versatility of the added side strap hole and showcase your personality in various creative",
        "descript4": "[Compatibility] Only compatible with iPhone 15 Pro & compatible with wireless charging and MagSafe wireless charging",
        "descript5": "[Enhanced Protection] We have optimized the design with a rear PC and side TPU to provide more stable protection for your device;"
    },
    {
        "id": 62,
        "image": "https://m.media-amazon.com/images/I/61PI5FSLBNL._SY450_.jpg",
        "pname": "USB C Wall Adapter,Compatible for iPhone",
        "category": "icharger",
        "brand": "apple",
        "originalPrice": 2999,
        "offerPrice": 1099,
        "descript1": "【20W PD 3.0 Fast Charge &15Mins Quick Charge】20W PD 3.0 USB Type C power delivery wall charger can provide a maximum of 20W output power to charge your device,this lastest PD3.0 Type-C Fast Charger can make you enjoy 90Mins usage time only charge 15Mins.",
        "descript2": "【3X Faster than Normal Charger】3 times faster than the original 5W charger, and this oraimo 20W PD 3.0 Type C Adapter Charger only takes 30 minutes to charge the iPhone up to 55%, saving you more than 1.5 hours.",
        "descript3": "【480Mbps Data Transfer and sync】 Fast Charging speed achieves data transfer rates up to 480Mbps. Fast transfer movies, music, and more between your USB-C equipped Mac and another Type C port device.",
        "descript4": "【Compatible for Apple Devices】with 1 m USB-C to Lighting Cable included,oraimo 20W fast Wall charger works for all iPhones models,suitable for iPhone 14/14 Plus/14 Pro/14 Pro Max/13/12/12 Pro Max/11/Xs Max/XR/X,AirPods Pr, iPad/iPad Mini, and More.",
        "descript5": "【Muti-protection Safe and Reliable】With the intelligent chip inside, The Power Delivery Wall Charger owns bulit-in multi-protection system，it matches the current as your device's need automatically."
    },
    {
        "id": 63,
        "image": "https://m.media-amazon.com/images/I/5111m0770WL._SX466_.jpg",
        "pname": "Dual Port Charger Type C Adapter",
        "category": "icharger",
        "brand": "apple",
        "originalPrice": 2999,
        "offerPrice": 1299,
        "descript1": "【Dual Port Fast Charging】This adapter is equipped with a USB-C Power Delivery (PD) port and a USB-A Quick Charge (QC) 3.0 port, which support fast charging of two devices simultaneously.",
        "descript2": "【Dr Vaku 35W Fast Charger Adapter】Fast Charger equipped with 35W PD 3.0 USB Type C power delivery wall plug. 35W adapter efficiently charges your phone up to 58% in about 30 minutes.",
        "descript3": "【Safe And Reliable】The adaptor’s strong, ABS Plastic built makes it safe to use even in clumsy hands. This charger with a built-in protection can protect your equipment from excessive current, overheating and overcharging.",
        "descript4": "【Lightweight & Portable Design】DR VAKU 35W Adapter is ultra-compact, portable and very convenient for business travellers to carry. The charger can be transported in a handbag, backpack, or carry-on luggage without taking up too much space.",
        "descript5": "【BIS Certified】The adapter is BIS certified for safety and reliability, ensuring that it meets the highest standards for quality and performance."
    },
    {
        "id": 64,
        "image": "https://m.media-amazon.com/images/I/41lJFlnT1kL._SX466_.jpg",
        "pname": "Wireless Charger with Fireproof ABS for iPhone",
        "category": "icharger",
        "brand": "apple",
        "originalPrice": 2599,
        "offerPrice": 1399,
        "descript1": "[ MADE IN INDIA ] RAEGR Arc One Qi - Certified provides short circuit prevention, surge protection, and temperature control. Made of ABS material which is fire-resistant and keeps the wireless charger running at a low temperature to ensure the highest charging speed",
        "descript2": "[ SLIM & UNIQUE AIR VENT DESIGN FOR TEMPERATURE CONTROL ] The Air Vent designs controls the temperature and its Advanced cooling feature helps better heat dissipation. The wireless charger is embedded with non-slip material and a matte finish surface to prevent it from slipping, this makes the charging more stable",
        "descript3": "[ CHARGING Through CASE] Ultra Thin Wireless Phone Charger can charge your phone with a Plastic/Rubber case on it under 5 mm thickness.",
        "descript4": "[PACKAGE & WARRANTY] Package contains 1 x Qi Wireless Charger Pad, 1 x 3.3ft Type-C USB Cable and 1 x User Manual & Warranty Card. We offer 1 Year Replacement Warranty against manufacturing defects . To activate the warranty, Kindly follow the instructions provided in the manual guidelines / leaflet .",
        "descript5": "Mag-Safe wireless chargers for iPhone 14/13/12 series for better performance"
    },
    {
        "id": 65,
        "image": "https://m.media-amazon.com/images/I/41-uqU+U2cL._SY300_SX300_.jpg",
        "pname": "Wireless Charger 3in1 23W Magnetic Mag-Safe",
        "category": "icharger",
        "brand": "apple",
        "originalPrice": 4999,
        "offerPrice": 2999,
        "descript1": "[ MADE IN INDIA ] RAEGR Arc One Qi - Certified provides short circuit prevention, surge protection, and temperature control. Made of ABS material which is fire-resistant and keeps the wireless charger running at a low temperature to ensure the highest charging speed",
        "descript2": "[ SLIM & UNIQUE AIR VENT DESIGN FOR TEMPERATURE CONTROL ] The Air Vent designs controls the temperature and its Advanced cooling feature helps better heat dissipation. The wireless charger is embedded with non-slip material and a matte finish surface to prevent it from slipping, this makes the charging more stable",
        "descript3": "[ CHARGING Through CASE] Ultra Thin Wireless Phone Charger can charge your phone with a Plastic/Rubber case on it under 5 mm thickness.",
        "descript4": "[PACKAGE & WARRANTY] Package contains 1 x Qi Wireless Charger Pad, 1 x 3.3ft Type-C USB Cable and 1 x User Manual & Warranty Card. We offer 1 Year Replacement Warranty against manufacturing defects . To activate the warranty, Kindly follow the instructions provided in the manual guidelines / leaflet .",
        "descript5": "Mag-Safe wireless chargers for iPhone 14/13/12 series for better performance"
    },
    {
        "id": 66,
        "image": "https://m.media-amazon.com/images/I/71sNnXEoWNL._SY355_.jpg",
        "pname": "Dell 14 Laptop",
        "category": "laptop",
        "brand": "dell",
        "originalPrice": 40000,
        "offerPrice": 35000,
        "descript1": "Processor: Intel Core i3-1215U 12th Generation (up to 4.40 GHz, 10MB 6 Cores)",
        "descript2": "RAM & Storage: 8 GB, 1 x 8 GB, DDR4, 2666 MHz, (2 DIMM Slots, Expandable up to 16GB) & 512GB SSD",
        "descript3": "Software: Pre-Loaded Windows 11 Home with Lifetime Validity | MS Office Home and Student 2021 with lifetime validity| McAfee Multi-Device Security 15-month subscription",
        "descript4": "Graphics & Keyboard: Integrated Onboard Graphics & Standard Keyboard // Display: 14.0",
        "descript5": "Battery- 3-Cell Battery, 41WHr"
    },
    {
        "id": 67,
        "image": "https://m.media-amazon.com/images/I/614aMDyKJXL._SX425_.jpg",
        "pname": "Dell 15 Vostro 3510 Laptop",
        "category": "laptop",
        "brand": "dell",
        "originalPrice": 66410,
        "offerPrice": 45990,
        "descript1": "Processor: Intel Core i5-1135G7 11th Generation Processor (up to 4.20 GHz, 8MB cache, 4 Cores)",
        "descript2": "RAM & Storage: 8 GB, 1 x 8 GB, DDR4, 3200 MHz & 512GB SSD",
        "descript3": "Software: Pre-Loaded Windows 11 Home with Lifetime Validity | MS Office Home and Student 2021 with lifetime validity| McAfee Multi Device Security 15-month subscription",
        "descript4": "Display & Keyboard: 15.6 FHD WVA AG 3 sided narrow border with FHD Display - TÜV Rheinland certified Dell ComfortView to reduce harmful blue light & Standard Keyboard",
        "descript5": "Warranty & Battery: 1 Year Onsite Hardware Service & 3-Cell Battery, 41WHr"
    },
    {
        "id": 68,
        "image": "https://m.media-amazon.com/images/I/51-OoAkxQqL._SX425_.jpg",
        "pname": "Dell Inspiron 3525 Laptop",
        "category": "laptop",
        "brand": "dell",
        "originalPrice": 40000,
        "offerPrice": 35000,
        "descript1": "Processor: AMD 5 Series Ryzen R3-5300U (up to 3.85 GHz. 2MB Cache + 4 Cores) // RAM: 8 GB, 1 x 8 GB, DDR4, 3200 MHz // Storage: 512GB SSD",
        "descript2": "Software: Pre-Loaded Windows 11 Home with Lifetime Validity | MS Office Home and Student 2021 with lifetime validity| McAfee Multi-Device Security 15-month subscription",
        "descript3": "Display: 15.6 FHD WVA AG Narrow Border 120Hz 250 nits // Graphics: Radeon Graphics",
        "descript4": "Ports: 1 USB 2.0 port, 1 Headset jack, 1 HDMI 1.4 port, 1 SD 3.0 card slot, 1 USB 3.2 Gen 1 port, 1 USB 3.2 Gen 1 Type-C port // Battery: 3-Cell Battery, 41WHr",
        "descript5": "Features: Refreshingly comfortable - Dell ComfortView helps reduce harmful blue light emissions // ExpressCharge - Charge your device up to 80% in an hour"
    },
    {
        "id": 69,
        "image": "https://m.media-amazon.com/images/I/71Z7zeSrbBL._SY355_.jpg",
        "pname": "Dell Inspiron 7430",
        "category": "laptop",
        "brand": "dell",
        "originalPrice": 80198,
        "offerPrice": 58990,
        "descript1": "Processor: Intel 13th Gen i3-1315U, up to 4.50 GHz, 10MB Cache + 6 Cores // RAM: 8 GB, LPDDR5, 4800 MHz, integrated // Storage: 1TB SSD",
        "descript2": "Included Software: Pre-Loaded Windows 11 Home with Lifetime Validity | MS Office Home and Student 2021 with lifetime validity| McAfee Multi Device Security 15-month subscription",
        "descript3": "Display: 14.0 FHD+ WVA with ComfortView Support 250 nits Touch // Graphics: Intel Iris Xe Graphics // Keyboard: Backlit Keyboard + Fingerprint Reader",
        "descript4": "Features: 16:10 aspect ratio on a 14-inch FHD+ display, Dolby Atmos spatial audio & Waves MaxxAudio Pro, FHD resolution camera, built in dual microphones and AI that reduces background noise from everyone on all the call, Get up-close and personal with loud and clear up-firing speakers for an exciting audio experience.",
        "descript5": "Ports: HDMI 1.4*, (2) Intel Thunderbolt 4.0, (1) USB 3.2 Gen 1 Type-A, SD card reader, (1) Universal Audio Jack // Battery: 4-Cell Battery, 54WHr"
    },
    {
        "id": 70,
        "image": "https://m.media-amazon.com/images/I/415KF4uonDL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "HP Chromebook",
        "category": "laptop",
        "brand": "hp",
        "originalPrice": 33578,
        "offerPrice": 22990,
        "descript1": "Processor: Intel Celeron N4120 (1.1 GHz base frequency(2b),up to 2.8 GHz burst frequency(2c), 4 MB L2 cache, 2 cores) | Memory & Storage: 4 GB LPDDR4-2400 MHz RAM (onboard) |64 GB eMMC, 100 GB Google Cloud storage (1 year)",
        "descript2": "Display: 35.6 cm (14) diagonal, HD touch, micro-edge, BrightView, 220 nits, 1366 x 768, 45% NTSC| Graphics: Intel UHD Graphics",
        "descript3": "Operating System & Software: Chrome 64| Google Assistant built-in",
        "descript4": "Networking: Realtek RTL8822CE 802.11a/b/g/n/ac Wi-Fi and Bluetooth 5 combo (Supporting Gigabit data rate) MU-MIMO supported",
        "descript5": "Ports: 2 SuperSpeed USB Type-C 5Gbps signaling rate (USB Power Delivery, DisplayPort 1.2), 1 SuperSpeed USB Type-A 5Gbps signaling rate, 1 headphone/microphone combo"
    },
    {
        "id": 71,
        "image": "https://m.media-amazon.com/images/I/71q31+pLWaL._SY355_.jpg",
        "pname": "HP Laptop 15s",
        "category": "laptop",
        "brand": "hp",
        "originalPrice": 33934,
        "offerPrice": 28599,
        "descript1": "【2-core Intel Celeron N4500】2 threads and 4MB L3 cache deliver fast processing speeds. The Intel UHD graphics help you dive into crisp, stunning visuals.",
        "descript2": "【Upgraded memory and storage】8GB DDR4 RAM and 512GB PCIe NVMe M.2 SSD allow you to undertake improved multitasking with high-bandwidth memory and ample storage. Now, browse or work as you please.",
        "descript3": "【Micro-edge display】The 15.6-inch, HD, 250-nit, and micro-edge display immerses you in your projects, helping you explore intricate details on a large screen.",
        "descript4": "【Effortless connectivity】Wi-Fi 5 (2x2) and Bluetooth 5.0 make you unstoppable with a dependable connection. Stay plugged in with 1 x USB Type-C, 2 x USB Type-A, and 1 x HDMI 1.4b ports.",
        "descript5": "【Long battery life】With HP Fast Charge, power up your device up to 50% in 45 mins. Once done, get ready to go where work takes you backed up with a long-lasting 41Wh battery life."
    },
    {
        "id": 72,
        "image": "https://m.media-amazon.com/images/I/51lMk8wpflL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "HP Victus Gaming Laptop",
        "category": "laptop",
        "brand": "hp",
        "originalPrice": 63629,
        "offerPrice": 47990,
        "descript1": "【6-core AMD Ryzen 5 5600H】12 threads and 16MB L3 cache enable you to dominate virtual battles with AMD SmartShift that dynamically adjusts power allocation between CPU and GPU to boost performance.",
        "descript2": "4 GB AMD Radeon RX 6500M graphics】Experience immersive, lifelike gameplay with 50W TGP  and accelerate heavy workflows with high-speed data processing, video editing, and rendering.",
        "descript3": "【Upgraded memory and storage】Make room for all your games with 512GB PCIe Gen4 NVMe TLC M.2 SSD. Plus, get 8GB DDR4 RAM that lets you take on any opponent with improved system responsiveness.",
        "descript4": "【Popular games】Play all your favourite games like League of Legends, Valorant, Fortnite, Call of Duty: Warzone, Apex Legends, Overwatch 2, Fall Guys, and more.",
        "descript5": "【Micro-edge display】The 15.6-inch, FHD, 250-nit , anti-glare, and micro-edge display keeps you in the thick of action with 82.23% screen-to-body ratio , reduced image ghosting, and crisp visuals"
    },
    {
        "id": 73,
        "image": "https://m.media-amazon.com/images/I/61WS4xoCvvL._SX355_.jpg",
        "pname": "HP ProBook 445 G8 Notebook",
        "category": "laptop",
        "brand": "hp",
        "originalPrice": 73268,
        "offerPrice": 45990,
        "descript1": "Processor: AMD Ryzen 7 5800U (up to 4.4 GHz max boost clock, 16 MB L3 cache, 8 cores, 16 threads)|Memory: 8 GB DDR4-3200 MHz RAM (1 x 8 GB)| Storage: 512 GB PCIe NVMe SSD",
        "descript2": "Display & Graphics: 35.6 cm (14) diagonal, FHD (1920 x 1080), IPS, anti-glare, 250 nits, 45% NTSC| Graphics: AMD Radeon Graphics",
        "descript3": "Operating System & Preinstalled Software: Dos",
        "descript4": "Ports:1 Stereo headphone/microphone combo jack; 3 SuperSpeed USB Type-A 5Gbps signaling rate (1 charging, 1 power); 1 HDMI 1.4b; 1 AC power; 1 RJ-45",
        "descript5": "Other Features: 720p HD Privacy camera|Audio: Dual stereo speakers, dual array microphones| Networking: Realtek 802.11a/b/g/n/ac (2x2) Wi-Fi and Bluetooth 5 wireless card| Keyboard & Pointing Device: Absolute persistence module|Battery: HP Long Life 3-cell, 45 Wh Li-ion"
    },
    {
        "id": 74,
        "image": "https://m.media-amazon.com/images/I/61xzutxSl8L._SY450_.jpg",
        "pname": "Acer Aspire 5 Gaming Laptop",
        "category": "laptop",
        "brand": "acer",
        "originalPrice": 82999,
        "offerPrice": 52990,
        "descript1": "Acer Aspire 5 Gaming laptop is powered by the latest 12th Gen Intel Core i5 processor consisting of 12 cores for multitasking and productivity",
        "descript2": "RTX It's On : NVIDIA GeForce RTX 2050 - 4G-GDDR6 laptops deliver ray tracing and cutting-edge AI features. The RTX 2050 also works seamlessly with NVIDIA Optimus technology to give you the perfect balance between long battery life and optimum performance. Over 150 top games and applications use RTX to deliver realistic graphics or cutting-edge new AI features like NVIDIA DLSS and NVIDIA Broadcast. RTX is the new standard.",
        "descript3": "Enhanced Cooling : Experience engineered solutions to maximize cooling with dual fans supporting multiple cooling modes and dual copper thermal pipes. Expel up to 10% more heat with the air inlet keyboard to keep your cool when it counts.",
        "descript4": "With Acer TNR Solution, experience intelligent image noise reduction in low-light conditions.",
        "descript5": "Internal Specifications : 16 GB of DDR4 system memory upgradable up to 32 GB using two soDIMM modules and 512GB PCIe NVMe Gen 4 SSD"
    },
    {
        "id": 75,
        "image": "https://m.media-amazon.com/images/I/41azBTqKhKL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Acer Aspire Lite",
        "category": "laptop",
        "brand": "acer",
        "originalPrice": 59990,
        "offerPrice": 35990,
        "descript1": "Processor : AMD Ryzen 5 5500U Hexa-Core Mobile Processor with AMD Radeon Graphics.Maximum Power Supply Wattage 45 W",
        "descript2": "Visibly Stunning: Experience sharp details and crisp colors on the 15.6 Full HD display, 16:9 aspect ratio, ultra-slim design and narrow bezels.",
        "descript3": "Internal Specifications: RAM - 16 GB of Dual-channel DDR4, 2 SODIMM sockets; Storage - 512 GB SSD NVMe solid-state drive storage (expandable up to 1TB) to store your files and media",
        "descript4": "Ports: 1 x USB 3.2 Gen 1 (Type A), 2 x USB 2.0 (Type A), 1 x USB 3.2 Gen 2 (Type C), 1 x DC-in jack",
        "descript5": "Keyboard: 100-/101-/104-key keyboard with independent numeric keypad, international language support"
    },
    {
        "id": 76,
        "image": "https://m.media-amazon.com/images/I/516qCPpFXkL._SX355_.jpg",
        "pname": "Acer Nitro V",
        "category": "laptop",
        "brand": "acer",
        "originalPrice": 92999,
        "offerPrice": 74990,
        "descript1": "Processor: Intel Core i5-13420H processor - 8 cores, max turbo up to 4.60 Ghz | RAM : 16 GB of DDR5 system memory, upgradable to 32 GB (Memory Frequency: Up to 5200 MT/s)",
        "descript2": "Display : 15.6 display with IPS (In-Plane Switching) technology, Full HD 1920 x 1080, Acer ComfyView LED-backlit TFT LCD, 16:9 aspect ratio, supporting 144 Hz refresh rate",
        "descript3": "Graphics : NVIDIA GeForce RTX 4050 with 6 GB of dedicated GDDR6",
        "descript4": "Storage : 512 GB SSD, PCIe Gen4, 16 Gb/s, NVMe ( Upgradable Upto 2*1 TB SSD) | OS : Windows 11 Home 64-bit",
        "descript5": "Ports: 1 x USB 3.2 Gen 1 port with power-off charging, 1 x USB 3.2 Gen 1 port, 1 x USB Type-C port (Thunderbolt ) | Features: Backlit keyboard"
    },
    {
        "id": 77,
        "image": "https://m.media-amazon.com/images/I/81E2srXhKVL._SY355_.jpg",
        "pname": "Acer Predator Helios Neo 16",
        "category": "laptop",
        "brand": "acer",
        "originalPrice": 148999,
        "offerPrice": 109990,
        "descript1": "New Intel Processor: Intel Core i7-13700HX Processor",
        "descript2": "Internal Specifications: Dual-channel DDR5 SDRAM support 16 (2*8) GB of DDR5 system memory, Upgradable up to 32 GB of DDR5 system memory",
        "descript3": "Display: 16.0 display with IPS (In-Plane Switching) technology, WUXGA 1920 x 1200, high-brightness (400 nits) Acer ComfyView LED-backlit TFT LCD, supporting 165 Hz, Grey to Grey 3 ms by Overdrive, Nvidia Advanced Optimus capable. 16:10 aspect ratio, sRGB 100%, Wide viewing angle up to 170 degrees, Ultra-slim design, Mercury free, environment friendly",
        "descript4": "Graphics: NVIDIA GeForce RTX 4050 with 6 GB of dedicated GDDR6 VRAM",
        "descript5": "Other Features: NVIDIA Advance Optimus, Liquid Metal 5th Gen Aeroblade 3D Fan, Full-Function Thunderbolt-4, HDMI 2.1"
    },
    {
        "id": 78,
        "image": "https://m.media-amazon.com/images/I/41T31LVvZ6L._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "soundcore Bluetooth Headphones",
        "category": "headphone",
        "brand": "soundcore",
        "originalPrice": 17999,
        "offerPrice": 8999,
        "descript1": "2X Stronger Voice Reduction: Stay focused during bustling journeys with our upgraded noise cancelling structure. Space One excels in blocking out mid to high-frequency sounds with 2X more* voice reduction. *Compared with soundcore Life Q30 headphones.",
        "descript2": "Reduce Noise By Up to 98%*: Adaptive noise cancelling detects external sounds and sound leakage, auto-calibrating to deliver optimal noise reduction. Escape unwanted distractions, whether you're on a noisy train, in a bustling café, or your headphones aren't sitting on your ears properly. *Tested by soundcore under laboratory conditions.",
        "descript3": "40 Hours of ANC Playtime: Embark on blissful journeys with 40 hours of playtime with ANC on. 55 hours of continuous music with ANC off ensures endless entertainment without battery concerns.",
        "descript4": "Crafted for Comfort and Style: Elegantly designed, 8° rotating ear cups effortlessly conform to the contours of any head, and a soft integrated headband evenly distributes pressure for natural prolonged wear.",
        "descript5": "84% positive ratings from 1K+ customers"
    },
    {
        "id": 79,
        "image": "https://m.media-amazon.com/images/I/61kFL7ywsZS._SY450_.jpg",
        "pname": "JBL Tune 510BT On Ear Wireless Headphones",
        "category": "headphone",
        "brand": "jbl",
        "originalPrice": 4499,
        "offerPrice": 2899,
        "descript1": "JBL PURE BASE SOUND: Packed with 32mm Dynamic drivers, the JBL Tune 510BT features the renowned JBL Pure Bass sound, which can be found in the most famous venues all around the world.",
        "descript2": "UPTO 40 HOURS PLAYTIME: Designed for long playhours, the Tune 510BT allows you to Listen wirelessly upto 40 hours non-stop under optimal audio settings.",
        "descript3": "QUICK CHARGING: With its superior USB Type-C charging cable, a quick 5 min recharge of your Tune 510BT provides you with playtime upto 2 Hours while in a span of 2 hours, get your headphones completely charged up.",
        "descript4": "DUAL PAIRING: The Multi Point Connectivity (Dual Pairing) on Tune 510BT allows youto effortlessly switch between 2 Bluetooth devices. Its a smooth transition when you have to receive a call on your mobile phone call while you are watching a video on your tab.",
        "descript5": "VOICE ASSISTANT INTEGRATION: Siri or Hey Google is just a button away: activate the voice assistant of your device by pushing the multi-function button on the earcup."
    },
    {
        "id": 80,
        "image": "https://m.media-amazon.com/images/I/61WFNqf8hVL._SY450_.jpg",
        "pname": "Sony WH-XB910N Headphone",
        "category": "headphone",
        "brand": "sony",
        "originalPrice": 19900,
        "offerPrice": 12931,
        "descript1": "Noise cancelling: Active Noise Cancellation (ANC) lends a personalized, virtually soundproof experience at any situation",
        "descript2": "Voice assistant: Alexa, Google Assistant & Siri enabled (In-built) for voice access to music, information and more. Activate with a simple touch",
        "descript3": "Quick attention mode: Cover the right ear cup with your palm to turn down music for instant, easy conversation",
        "descript4": "Smart listening: WH-XB910N adjusts the ambient sound to your activity to give you the best noise cancellation",
        "descript5": "Long battery life/Quick Charge: A single charge provides up to 30 hrs of playtime for reliable all day listening and Quick charge for 10min charge for 4.5 hours play back"
    },
    {
        "id": 81,
        "image": "https://m.media-amazon.com/images/I/61vvmibZy8L._SY450_.jpg",
        "pname": "ZEBRONICS Thunder Headphone",
        "category": "headphone",
        "brand": "zebronics",
        "originalPrice": 1399,
        "offerPrice": 699,
        "descript1": "Comfortable Design: Beat the workday blues with music on Zeb-Thunder wireless headphone that comes in an ergonomic design a perfect fit and design for long hours use. Microphone sensitivity -40dB ±1dB. Microphone impedance 1.2k Ω",
        "descript2": "Soft & comfortable earcups: Listen to music, podcasts and more for long hours with soft ear cups making it super comfortable for daily wear",
        "descript3": "Adjustable headband: Adust your headband to your comfortable best while you work or listen to music",
        "descript4": "9hrs Playback Time: Fall in love with the audio experience with 9 hours of playback time to keep you going. Sensitivity : -113dB ±3dB",
        "descript5": "Superior Sound Quality: Magnify every speck of sound with superior sound quality on Zeb-Thunder wireless headphone"
    },
    {
        "id": 82,
        "image": "https://m.media-amazon.com/images/I/61bodEi+1JL._SY450_.jpg",
        "pname": "Noise Wireless Earbuds",
        "category": "earbuds",
        "brand": "noise",
        "originalPrice": 4499,
        "offerPrice": 1799,
        "descript1": "Up to 120-hour playtime: Unleash a sonic marathon with earbuds that defy the clock.",
        "descript2": "Quad mic with ENC: Experience exceptional call clarity even in noisy environments.",
        "descript3": "11mm driver: Immerse yourself in rich, high-quality sound courtesy of our powerful audio drivers.",
        "descript4": "InstachargeTM (10-min charge = 200-min playtime): Enjoy your music without interruption with super-fast charging that offers hours of playback in just 10 minutes.",
        "descript5": "Low latency (up to 50ms): Conquer lag and immerse yourself in a gaming experience that's truly seamless."
    },
    {
        "id": 83,
        "image": "https://m.media-amazon.com/images/I/51oMWaW7tKL._SY450_.jpg",
        "pname": "OnePlus Nord Earbuds ",
        "category": "earbuds",
        "brand": "oneplus",
        "originalPrice": 2299,
        "offerPrice": 2199,
        "descript1": "[Enhanced Sound Experience]: The buds comes with 12.4mm driver unit, which delivers crisp clear and enhanced bass quality sound experience",
        "descript2": "[Sound Master Equalizers]: For the OnePlus Nord Buds 2r, you get to choose how heavy or light you want your sound with the help of sound master equalizer’s 3 unique audio profiles -Bold, Bass & Balanced",
        "descript3": "[Battery Life]:The flagship-level battery life for the all-new OnePlus Nord Buds 2r delivers up to 38 hrs of non-stop music on a single charge.",
        "descript4": "[IP55 rating]: IP55 Water & Sweat Resistance",
        "descript5": "[Gaming Mode]: It allows users to access a plethora of features while playing supported games on a OnePlus handset. They can be accessed at any time while playing games and give players the option to toggle different features and settings"
    },
    {
        "id": 84,
        "image": "https://m.media-amazon.com/images/I/61UW9gEiOSL._SY450_.jpg",
        "pname": "realme TechLife Buds",
        "category": "earbuds",
        "brand": "realme",
        "originalPrice": 2999,
        "offerPrice": 1399,
        "descript1": "AI Environment Noise Cancellation for calls",
        "descript2": "Upto 28 hrs of Total Playback | Fast charging - 10 min charge gives upto 120 min playback",
        "descript3": "10mm Dynamic Bass Driver for Real HD Sound",
        "descript4": "Instant Connection with Google Fast Pair | Intelligent Touch Controls",
        "descript5": "realme Link App connectivity"
    },
    {
        "id": 85,
        "image": "https://m.media-amazon.com/images/I/61G5JoU9tTL._SY450_.jpg",
        "pname": "Samsung Galaxy Buds",
        "category": "earbuds",
        "brand": "samsung",
        "originalPrice": 15990,
        "offerPrice": 4299,
        "descript1": "1 year warranty provided by the manufacturer from date of purchase.Note : If the size of the earbud tips does not match the size of your ear canals or the headset is not worn properly in your ears, you may not obtain the correct sound qualities or call performance. Change the earbud tips to ones that fit more snugly in your ears",
        "descript2": "Crystal clear voice & call quality with 3 mics & a Voice Pick Up unit",
        "descript3": "Deep & spacious sound tuned by AKG. Sensors: Accelerometer, Gyro, Proximity, Hall, Touch, Grip, VPU",
        "descript4": "Eye-catching design in a glossy finish that keeps you connected yet comfortable through the day",
        "descript5": "Buds, Charging Case, user manual"
    },
    {
        "id": 86,
        "image": "https://m.media-amazon.com/images/I/71xQq6cAhGL._SY550_.jpg",
        "pname": "Titan Neo Iv Analog Black Dial Men's Watch",
        "category": "watch",
        "brand": "titan",
        "originalPrice": 7645,
        "offerPrice": 7145,
        "descript1": "Dial Color: Black, Case Shape: Round, Dial Glass Material: Mineral",
        "descript2": "Band Color: Black, Band Material: Metal. Function : Multifunction",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "Case Material: Brass, Case Diameter: 49.2 millimeters. Case Width(3H-9H) 42 mm. Case Thickness 11.2 mm",
        "descript5": "Water Resistance Depth: 50 meters, Buckle Clasp"
    },
    {
        "id": 87,
        "image": "https://m.media-amazon.com/images/I/51ULWKNrvPL._SX569_.jpg",
        "pname": "Titan Brown Dial Analog Watch ",
        "category": "watch",
        "brand": "titan",
        "originalPrice": 5000,
        "offerPrice": 3075,
        "descript1": "Dial Color: Brown, Case Shape: Round, Dial Glass Material: Mineral",
        "descript2": "Band Color: Brown, Band Material: Leather. The watch has a buckle lock mechanism",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "Case Material: Metal, FUNCTION: Analog with Date",
        "descript5": "Water Resistance Depth: 50 meters"
    },
    {
        "id": 88,
        "image": "https://m.media-amazon.com/images/I/71U5K4yPj3L._SY550_.jpg",
        "pname": "Titan Karishma Analog Men's Watch",
        "category": "watch",
        "brand": "titan",
        "originalPrice": 3545,
        "offerPrice": 3365,
        "descript1": "Dial Color: Silver, Case Shape: Round, Dial Glass Material: Mineral",
        "descript2": "Band Color: Gold, Band Material: Stainless Steel",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "Case Material: Brass, Case Diameter: 47 millimeters",
        "descript5": "Water Resistance Depth: 30 meters"
    },
    {
        "id": 89,
        "image": "https://m.media-amazon.com/images/I/719wzn0TOlL._SY550_.jpg",
        "pname": "Titan Anthracite Dial Analog Watch",
        "category": "watch",
        "brand": "titan",
        "originalPrice": 6000,
        "offerPrice": 4500,
        "descript1": "Dial Color: Black, Case Shape: Round",
        "descript2": "Band Color: Off-White, Band Material: Stainless Steel",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "24 Months Manufacturer Warranty",
        "descript5": "Water Resistance: 5 ATM"
    },
    {
        "id": 90,
        "image": "https://m.media-amazon.com/images/I/51drkXAd7ZL._SX569_.jpg",
        "pname": "Fastrack Black Dial Analog Watch",
        "category": "watch",
        "brand": "fastrack",
        "originalPrice": 1000,
        "offerPrice": 795,
        "descript1": "Dial Color: Black, Case Shape: Round",
        "descript2": "Band Color: Black, Band Material: Plastic",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "Case Material: Plastic",
        "descript5": "Water Resistance Depth: 30 meters"
    },
    {
        "id": 91,
        "image": "https://m.media-amazon.com/images/I/51a3+s+2hUL._SX569_.jpg",
        "pname": "Fastrack Grey Dial Analog Watch",
        "category": "watch",
        "brand": "fastrack",
        "originalPrice": 3000,
        "offerPrice": 2395,
        "descript1": "Dial Color: Grey, Case Shape: Round, Dial Glass Material: Acrylic",
        "descript2": "Band Color: Grey, Band Material: Silicone",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "Case Material: Plastic, Case Diameter: 51 millimeters. Lock Mechanism : Buckle",
        "descript5": "Water Resistance Depth: 100 meters"
    },
    {
        "id": 92,
        "image": "https://m.media-amazon.com/images/I/51bzah11WpL._SX569_.jpg",
        "pname": "Fastrack Casual Analog White",
        "category": "watch",
        "brand": "fastrack",
        "originalPrice": 1895,
        "offerPrice": 1700,
        "descript1": "Dial Color: White, Case Shape: Round, Dial Glass Material: Mineral.",
        "descript2": "Band Color: Silver, Band Material: Stainless Steel ; Lock Mechanism: Diver's Clasp ; Case Shape: Round",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "Case Material: Metal, Case Thickness(mm):11.8 mm; Case Length(6H-12H)(mm):52 mm; Case",
        "descript5": "Water Resistance Depth: 50 meters, Buckle Clasp"
    },
    {
        "id": 93,
        "image": "https://m.media-amazon.com/images/I/51UyQD7kUDL._SX569_.jpg",
        "pname": "Fastrack Black Dial Analog Watch",
        "category": "watch",
        "brand": "fastrack",
        "originalPrice": 1900,
        "offerPrice": 1500,
        "descript1": "Dial Color: White, Case Shape: Round, Dial Glass Material: Mineral.",
        "descript2": "Band Color: Silver, Band Material: Stainless Steel ; Lock Mechanism: Diver's Clasp ; Case Shape: Round",
        "descript3": "Watch Movement Type: Quartz, Watch Display Type: Analog",
        "descript4": "Case Material: Metal, Case Thickness(mm):11.8 mm; Case Length(6H-12H)(mm):52 mm; Case",
        "descript5": "Water Resistance Depth: 50 meters, Buckle Clasp"
    },
    {
        "id": 94,
        "image": "https://m.media-amazon.com/images/I/515EX2dUR9L._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Fire-Boltt Phoenix Smartwatch",
        "category": "smartwatch",
        "brand": "firebolt",
        "originalPrice": 12499,
        "offerPrice": 1999,
        "descript1": "【Bigger Round Display】- Comes with a TFT Color Full Touch Screen and a 240*240 Pixel High Resolution this watch is covered to flaunt the sleek and stylish look always. Enjoy a 320 NITS Peak Brightness",
        "descript2": "The watch will work on a single charge for about 7 days (without Bluetooth calling) and about 4 Days with Bluetooth calling. 【Stainless Steel Luxury Straps】- Fire-Boltt Phoenix Ultra has stainless steel magnetic closure straps for ultimate luxury look and sleek finish",
        "descript3": "Charging Specs - The watch needs to be charged for 3 hours to reach 100%. The charger should be a 3.7V to 5V adapter or any laptop output. For a bare minimum of 20% charge the watch needs to be charged for about 30-40 mins",
        "descript4": "You cannot store Music in the watch, you can only control the music. 【Bluetooth Calling Watch】- Fire-Boltt Pheonix Ultra enables you to make and receive calls directly from your watch via the built-in speaker and microphone.",
        "descript5": "There is no volume control, however when connected to bt calling you can control the volume of the call. 【120+ Sports Modes】- Track each activity effectively with this smartwatch & activity tracker."
    },
    {
        "id": 95,
        "image": "https://m.media-amazon.com/images/I/41btsr8T+tL._SY300_SX300_.jpg",
        "pname": "Fire-Boltt Ninja 3 Smartwatch",
        "category": "smartwatch",
        "brand": "firebolt",
        "originalPrice": 7999,
        "offerPrice": 1099,
        "descript1": "Fire-Boltt is India' No 1 Wearable Watch Brand Q122 by IDC Worldwide quarterly wearable device tracker Q122.【1.69” HD Large Touch Screen】- Fire-Boltt Ninja 3 comes with a 1.69” HD Full Touch Display for smooth swipes and clear vision;【SPO2/ Oxygen, Heart Rate】 - Fire-Boltt Ninja 3 Smartwatch comes with real time 24*7 SPO2 / Blood Oxygen tracking, Dynamic Heart Rate Monitoring (If a patient is suffering from Covid 19 please use a medical device prescribed by the Doctor)",
        "descript2": "【60 workout modes】- This smartwatch consists of 60 sports mode to track. Keep a track of all your activities and compare history to analyse your performance. Count steps, distance, and calories burned.;【IP68 Water Resistant】- This smartwatch can withstand dust, spills, raindrops and is sweatproof too",
        "descript3": "Charging Specs - The watch needs to be charged for 3 hours to reach 100%. The charger should be a 3.7V to 5V adapter or any laptop output. For a bare minimum of 20% charge the watch needs to be charged for about 30-40 mins",
        "descript4": "【POWERFUL BATTERY】 - About 7 days battery life and a Standby Time of 25 Days 【Multiple Watch Faces】- Unlimited Customized Built in Watch Faces and also multiple watch faces through the app;【Stay Social Stay Updated】 – Inbuilt Social Media Notifications.",
        "descript5": "Supported Applications - Notifcations from all social media channels (Instagram, Whatsapp, Facebook), Call Notifications, Health Tracking (SpO2, Heart Rate, Sleep), Sports Tracking & many more"
    },
    {
        "id": 96,
        "image": "https://m.media-amazon.com/images/I/41NlfK4IEfL._SX300_SY300_QL70_FMwebp_.jpg",
        "pname": "Fire-Boltt Talk 2",
        "category": "smartwatch",
        "brand": "firebolt",
        "originalPrice": 9999,
        "offerPrice": 1299,
        "descript1": "【1.28 inch HD Display】- This smartwatch has a 1.28” TFT LCD Full Touch Display with a 2D High Hardness Glass for super protection and a high resolution of 240*240 pixels. The watch has 600 NITS Peak Brightness",
        "descript2": "【 Battery Life】- The watch can work for 3 Days with Bluetooth Calling ( Normal Usage )*, 8 Days without Bluetooth Calling. System requirements: Bluetooth version 5.0 and above. IOS 7.0 and above, Android version 4.4 and above.",
        "descript3": "Charging Specs - The watch needs to be charged for 3 hours to reach 100%. The charger should be a 3.7V to 5V adapter or any laptop output. For a bare minimum of 20% charge the watch needs to be charged for about 30-40 mins",
        "descript4": "There is no volume control, however when connected to bt calling you can control the volume of the call. 【Built In Mic & Speaker】- Enjoy listening to your favour ite tunes on the watch and experience HD Calling through the built in Mic",
        "descript5": "Supported Applications - Notifcations from all social media channels (Instagram, Whatsapp, Facebook), Call Notifications, Health Tracking (SpO2, Heart Rate, Sleep), Sports Tracking & many more"
    },
    {
        "id": 97,
        "image": "https://m.media-amazon.com/images/I/61ivtsRO9LL._SX425_.jpg",
        "pname": "beatXP Flare Pro 1.39",
        "category": "smartwatch",
        "brand": "beatxp",
        "originalPrice": 5499,
        "offerPrice": 1199,
        "descript1": "1.39” Ultra HD Display Smartwatch: Experience the convenience and luxury of our 1.39” round Ultra HD Display smart watch with a 60Hz Refresh rate and 500 Nits Brightness that keeps you connected in style. Get the most out of your smartwatch with our cutting-edge features and sophisticated design.",
        "descript2": "Advanced Bluetooth Calling: The Flare Pro is a bluetooth calling smart watch powered by EzyPair Technology that allows you to answer calls directly from your wrist, freeing you from the hassle of constantly reaching for your phone.",
        "descript3": "24/7 Health Tracking: Stay on top of your wellness with our 24/7 health tracking feature, monitoring your heart rate, sleep patterns, SpO2 and more.",
        "descript4": "IP68 Water Resistance: This beatXP Flare Pro smartwatch is also IP68 water-resistant, making it the perfect choice for spontaneous adventures or even a quick swim. This makes it the perfect smartwatch for men and women.",
        "descript5": "Menstrual Alerts: Never be caught off guard again with our thoughtful menstrual cycle reminders, exclusively designed for our female users. This makes Flare Pro an excellent smartwatch for women."
    },
    {
        "id": 98,
        "image": "https://m.media-amazon.com/images/I/61lKQWyMdDL._SX679_.jpg",
        "pname": "Apple iPhone 14 Pro (128 GB)",
        "category": "mobile",
        "brand": "apple",
        "model": "Iphone14",
        "originalPrice": 129999,
        "offerPrice": 111999,
        "descript1": "16.95 cm (6.7-inch) Super Retina XDR display",
        "descript2": "Advanced camera system for better photos in any light",
        "descript3": "All-day battery life and up to 26 hours of video playback",
        "descript4": "Industry-leading durability features with Ceramic Shield and water resistance",
        "descript5": "Action mode for smooth, steady, handheld videos"
    }
];


module.exports = data;